[project]
name = "language-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.181.0",
    "google-cloud>=0.34.0",
    "google-cloud-vision>=3.10.2",
]
